apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ucrm.fullname" . }}
  labels:
    {{- include "ucrm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "ucrm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ucrm.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "ucrm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Values.global.ucrm.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: http-suspend
              containerPort: 81
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: http
          readinessProbe:
            tcpSocket:
              port: http
          startupProbe:
            tcpSocket:
              port: http
            failureThreshold: 90
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          args:
            - server_with_migrate
          env:
            {{- range $name, $value := .Values.env }}
            - name: {{ $name | quote }}
              value: {{ $value | quote }}
            {{- end }}
          volumeMounts:
            - name: unms-data
              mountPath: /data
              subPath: ucrm
      initContainers:
        {{ include "common.initContainersWaitForServices" . | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      enableServiceLinks: no
      volumes:
        - name: unms-data
          persistentVolumeClaim:
            claimName: {{ .Values.global.persistence.unmsPvcName }}
        # - name: ucrm-data
        # {{- if .Values.persistence.enabled }}
        #   persistentVolumeClaim:
        #   {{- if .Values.persistence.existingClaim }}
        #     claimName: {{ .Values.persistence.existingClaim }}
        #   {{- else }}
        #     claimName: {{ include "ucrm.fullname" . }}
        #   {{- end }}
        # {{- else }}
        #   emptyDir: {}
        # {{- end }}
