apiVersion: v1
kind: Service
metadata:
  name: {{ include "ucrm.fullname" . }}
  labels:
    {{- include "ucrm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      
    - name: http-suspend
      port: 81
      protocol: TCP
  selector:
    {{- include "ucrm.selectorLabels" . | nindent 4 }}
