{{- if .Values.tls.enabled -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "{{ include "mongodb.fullname" . }}-server-tls"
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  secretName: "{{ include "mongodb.fullname" . }}-server-tls"
  duration: 2160h0m0s # 90d
  renewBefore: 360h0m0s # 15d
  revisionHistoryLimit: 10
  subject:
    organizations:
      - benfu-me
  privateKey:
    algorithm: Ed25519
    encoding: PKCS8
    rotationPolicy: Always
  usages:
    - digital signature
    - key encipherment
    - server auth
    - client auth
  commonName: "*.{{ include "mongodb.fullname" . }}-svc.{{ .Release.Namespace }}.svc.cluster.local"
  dnsNames:
    - "{{ include "mongodb.fullname" . }}-svc"
    - "*.{{ include "mongodb.fullname" . }}-svc"
    - "{{ include "mongodb.fullname" . }}-svc.{{ .Release.Namespace }}"
    - "*.{{ include "mongodb.fullname" . }}-svc.{{ .Release.Namespace }}"
    - "{{ include "mongodb.fullname" . }}-svc.{{ .Release.Namespace }}.svc.cluster.local"
    - "*.{{ include "mongodb.fullname" . }}-svc.{{ .Release.Namespace }}.svc.cluster.local"
  issuerRef:
    {{- toYaml .Values.certificateIssuerRef | nindent 4 }}
{{- end }}
