apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "mongodb.fullname" . }}-init-db"
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
    # argocd.argoproj.io/sync-wave: "1"
    # argocd.argoproj.io/hook: PostSync
    # argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  backoffLimit: 0
  # activeDeadlineSeconds: 60
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: "{{ include "mongodb.fullname" . }}-mongodb"
      terminationGracePeriodSeconds: 0
      containers:
        - name: mongo-init-db
          image: ubuntu:22.04
          imagePullPolicy: IfNotPresent
          command:
            - /bin/bash
            - -c
          args:
            - /etc/initdb/bootstrap.sh

            # - "{{ include "mongodb.fullname" . }}-mongodb-svc:27017/admin"
            # - /etc/initdb/init-db.js
          env:
            - name: MONGODB_URL
              valueFrom:
                secretKeyRef:
                  name: "{{ include "mongodb.fullname" . }}-mongodb-client-admin-creds"
                  key: connectionString.standard
            - name: MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: "{{ include "mongodb.fullname" . }}-mongodb-client-admin-creds"
                  key: username
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ include "mongodb.fullname" . }}-mongodb-client-admin-creds"
                  key: password
          volumeMounts:
            - name: init-scripts
              mountPath: /etc/initdb
              readOnly: true
      volumes:
        - name: init-scripts
          configMap:
            name: "{{ include "mongodb.fullname" . }}-init-db"
            defaultMode: 0755
