apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "mongodb.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "mongodb.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "mongodb.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
