---
kind: pipeline
type: kubernetes
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: greeting
    image: alpine/helm
    commands:
      - echo hello world
      - echo here
      - git status
