---
kind: pipeline
type: kubernetes
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: Publish chart
    image: alpine/helm
    commands:
      - apk update && apk upgrade && apk add --no-cache git bash
      - ./deploy.sh
