{{/*
`common.container.tpl` defines a container definition.
See: https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#Container
This takes a dict with the following keys:
- .rootCtx: the root context
- (optional) .containerValues: the portion of the Helm values map for the container. Defaults to the root values (`.Values`)
- (optional) .componentName: the component name if this is part of a multi-component app
*/}}
{{- define "common.container.tpl" -}}
{{- $rootCtx := .rootCtx -}}
{{- $containerValues := .templateValues | default $rootCtx.Values -}}
{{- $componentName := .componentName | default "" -}}
name: {{ $containerValues.containerName | default (include "common.fullComponentName" (dict "rootCtx" $rootCtx "componentName" $componentName)) }}
securityContext:
  {{- toYaml $containerValues.securityContext | nindent 2 }}
image: "{{ $containerValues.image.repository }}:{{ $containerValues.image.tag | default $rootCtx.Chart.AppVersion }}"
imagePullPolicy: {{ $containerValues.image.pullPolicy }}
{{- with $containerValues.command }}
command:
  {{- tpl (toYaml .) $rootCtx | nindent 2 }}
{{- end }}
{{- with $containerValues.args }}
args:
  {{- tpl (toYaml .) $rootCtx | nindent 2 }}
{{- end }}
env:
  {{- with $containerValues.env }}
  {{- tpl (toYaml .) $rootCtx | nindent 2 }}
  {{- end }}
{{- with $containerValues.envFrom }}
envFrom:
  {{- toYaml . | nindent 2 }}
{{- end }}
ports:
  {{- range $portName, $portValues := (($containerValues.service).ports) }}
  - name: {{ $portName | quote }}
    containerPort: {{ $portValues.containerPort | default $portValues.port | int }}
    protocol: {{ $portValues.protocol | default "TCP" | quote }}
  {{- end }}
{{- with $containerValues.livenessProbe }}
livenessProbe:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- with $containerValues.livenessProbe }}
livenessProbe:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- with $containerValues.readinessProbe }}
readinessProbe:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- with $containerValues.startupProbe }}
startupProbe:
  {{- toYaml . | nindent 2 }}
{{- end }}
resources:
  {{- toYaml $containerValues.resources | nindent 2 }}
{{- with $containerValues.volumeMounts }}
volumeMounts:
  {{ tpl (toYaml .) $rootCtx | nindent 2 }}
{{- end }}
{{- end -}}

{{/*
`common.container` merges the container definition in `common.container.tpl` with overrides defined the helm values.
This takes a dict with the following keys:
- .rootCtx: the root context
- (optional) .containerValues: the portion of the Helm values map for the container. Defaults to the root values (`.Values`)
- (optional) .containerOverrides: the template name of the container overrides defined by the application chart
*/}}
{{- define "common.container" -}}
{{- $rootCtx := .rootCtx -}}
{{- $containerValues := .containerValues | default $rootCtx.Values -}}
{{- $containerOverrides := .containerOverrides | default "common.defaultEmptyOverrides" -}}
{{- $componentName := .componentName | default "" -}}
{{- include "common.util.merge" (dict "rootCtx" $rootCtx "templateValues" $containerValues "sourceTemplate" "common.container.tpl" "overridesTemplate" $containerOverrides "componentName" $componentName) -}}
{{- end -}}
