{{/*
`common.daemonSet.tpl` defines a daemonset definition.
See: https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/daemon-set-v1/
This takes a dict with the following keys:
- .rootCtx: the root context
- (optional) .templateValues: the portion of the Helm values map for the daemonset. Defaults to the root values (`.Values`)
- (optional) .componentName: the component name if this is part of a multi-component app
*/}}
{{- define "common.daemonSet.tpl" -}}
{{- $rootCtx := .rootCtx -}}
{{- $daemonSetValues := .templateValues | default $rootCtx.Values -}}
{{- $componentName := .componentName | default "" -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "common.fullComponentName" (dict "rootCtx" $rootCtx "componentName" $componentName) }}
  namespace: {{ $rootCtx.Release.Namespace | quote }}
  labels:
    {{- include "common.labels" $rootCtx | nindent 4 }}
    {{- include "common.componentLabels" (dict "rootCtx" $rootCtx "componentName" $componentName) | nindent 4 }}
spec:
  {{- with $daemonSetValues.updateStrategy }}
  updateStrategy:
    {{ toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "common.selectorLabels" $rootCtx | nindent 6 }}
      {{- include "common.componentSelectorLabels" (dict "rootCtx" $rootCtx "componentName" $componentName) | nindent 6 }}
  template:
    {{- include "common.pod.tpl" (dict "rootCtx" $rootCtx "templateValues" $daemonSetValues "componentName" $componentName) | nindent 4 }}
{{- end }}

{{/*
`common.daemonSet` merges the daemonset definition in `common.daemonSet.tpl` with overrides defined the helm values.
This takes a dict with the following keys:
- .rootCtx: the root context
- (optional) .daemonSetValues: the portion of the Helm values map for the daemonset. Defaults to the root values (`.Values`)
- (optional) .daemonSetOverrides: the template name of the daemonset overrides defined by the application chart
*/}}
{{- define "common.daemonSet" -}}
{{- $rootCtx := .rootCtx -}}
{{- $daemonSetValues := .daemonSetValues | default $rootCtx.Values -}}
{{- $daemonSetOverrides := .daemonSetOverrides | default "common.defaultEmptyOverrides" -}}
{{- $componentName := .componentName | default "" -}}
{{- include "common.util.merge" (dict "rootCtx" $rootCtx "templateValues" $daemonSetValues "sourceTemplate" "common.daemonSet.tpl" "overridesTemplate" $daemonSetOverrides "componentName" $componentName) -}}
{{- end -}}
