{{/*
`common.deployment.tpl` defines a deployment definition.
See: https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/deployment-v1/#Deployment
This takes a dict with the following keys:
- .rootCtx: the root context
- (optional) .deploymentValues: the portion of the Helm values map for the deployment. Defaults to the root values (`.Values`)
- (optional) .componentName: the component name if this is part of a multi-component app
*/}}
{{- define "common.deployment.tpl" -}}
{{- $rootCtx := .rootCtx -}}
{{- $deploymentValues := .templateValues | default $rootCtx.Values -}}
{{- $componentName := .componentName | default "" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.fullComponentName" (dict "rootCtx" $rootCtx "componentName" $componentName) }}
  namespace: {{ $rootCtx.Release.Namespace | quote }}
  labels:
    {{- include "common.labels" $rootCtx | nindent 4 }}
    {{- include "common.componentLabels" (dict "rootCtx" $rootCtx "componentName" $componentName) | nindent 4 }}
spec:
  {{- if not $deploymentValues.autoscaling.enabled }}
  replicas: {{ $deploymentValues.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "common.selectorLabels" $rootCtx | nindent 6 }}
      {{- include "common.componentSelectorLabels" (dict "rootCtx" $rootCtx "componentName" $componentName) | nindent 6 }}
  template:
    {{- include "common.pod.tpl" (dict "rootCtx" $rootCtx "templateValues" $deploymentValues "componentName" $componentName) | nindent 4 }}
{{- end }}

{{/*
`common.deployment` merges the deployment definition in `common.deployment.tpl` with overrides defined the helm values.
This takes a dict with the following keys:
- .rootCtx: the root context
- (optional) .deploymentValues: the portion of the Helm values map for the deployment. Defaults to the root values (`.Values`)
- (optional) .deploymentOverrides: the template name of the deployment overrides defined by the application chart
*/}}
{{- define "common.deployment" -}}
{{- $rootCtx := .rootCtx -}}
{{- $deploymentValues := .deploymentValues | default $rootCtx.Values -}}
{{- $deploymentOverrides := .deploymentOverrides | default "common.defaultEmptyOverrides" -}}
{{- $componentName := .componentName | default "" -}}
{{- include "common.util.merge" (dict "rootCtx" $rootCtx "templateValues" $deploymentValues "sourceTemplate" "common.deployment.tpl" "overridesTemplate" $deploymentOverrides "componentName" $componentName) -}}
{{- end -}}
