{{/*
`common.externalsecret.tpl` defines a secret definition.
See: https://external-secrets.io/v0.4.4/api-externalsecret/
This takes a dict with the following keys:
- .rootCtx: the root context
- (optional) .secretValues: the portion of the Helm values map for the externalsecret. Defaults to the root values (`.Values`)
- (optional) .componentName: the component name if this is part of a multi-component app
*/}}
{{- define "common.externalsecret.tpl" -}}
{{- $rootCtx := .rootCtx -}}
{{- $secretValues := .templateValues | default $rootCtx.Values -}}
{{- $componentName := .componentName | default "" -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "{{ include "common.fullComponentName" (dict "rootCtx" $rootCtx "componentName" $componentName) }}-{{ $secretValues.name }}"
  namespace: {{ $rootCtx.Release.Namespace | quote }}
  labels:
    {{- include "common.labels" $rootCtx | nindent 4 }}
    {{- include "common.componentLabels" (dict "rootCtx" $rootCtx "componentName" $componentName) | nindent 4 }}
spec:
  secretStoreRef:
    name: {{ $secretValues.storeName | default $rootCtx.Values.global.externalSecrets.storeName | quote }}
    kind: ClusterSecretStore
  refreshInterval: 30m
  target:
    name: "{{ include "common.fullComponentName" (dict "rootCtx" $rootCtx "componentName" $componentName) }}-{{ $secretValues.name }}"
    creationPolicy: Owner
    {{- with $secretValues.template }}
    template:
      {{- tpl (toYaml .) $rootCtx | nindent 6 }}
    {{- end }}
  {{- with $secretValues.data }}
  data:
    {{- tpl (toYaml .) $rootCtx | nindent 4 }}
  {{- end }}
  {{- with $secretValues.dataFrom }}
  dataFrom:
    {{- tpl (toYaml .) $rootCtx | nindent 4 }}
  {{- end }}
{{- end }}

{{/*
`common.externalsecret` merges the externalsecret definition in `common.externalsecret.tpl` with overrides defined the helm values.
This takes a dict with the following keys:
- .rootCtx: the root context
- (optional) .secretValues: the portion of the Helm values map for the externalsecret. Defaults to the root values (`.Values`)
- (optional) .secretOverrides: the template name of the externalsecret overrides defined by the application chart
*/}}
{{- define "common.externalsecret" -}}
{{- $rootCtx := .rootCtx -}}
{{- $secretValues := .secretValues | default $rootCtx.Values -}}
{{- $secretOverrides := .secretOverrides | default "common.defaultEmptyOverrides" -}}
{{- $componentName := .componentName | default "" -}}
{{- include "common.util.merge" (dict "rootCtx" $rootCtx "templateValues" $secretValues "sourceTemplate" "common.externalsecret.tpl" "overridesTemplate" $secretOverrides "componentName" $componentName) -}}
{{- end -}}
