{{/*
`common.hpa.tpl` defines a hpa definition.
See: https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/horizontal-pod-autoscaler-v2/#HorizontalPodAutoscaler
This takes a dict with the following keys:
- .rootCtx: the root context
- (optional) .hpaValues: the portion of the Helm values map for the hpa. Defaults to the root values (`.Values`)
- (optional) .componentName: the component name if this is part of a multi-component app
*/}}
{{- define "common.hpa.tpl" -}}
{{- $rootCtx := .rootCtx -}}
{{- $hpaValues := .templateValues | default $rootCtx.Values -}}
{{- $componentName := .componentName | default "" -}}
{{- if $hpaValues.autoscaling.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "common.fullComponentName" (dict "rootCtx" $rootCtx "componentName" $componentName) }}
  namespace: {{ $rootCtx.Release.Namespace | quote }}
  labels:
    {{- include "common.labels" $rootCtx | nindent 4 }}
    {{- include "common.componentLabels" (dict "rootCtx" $rootCtx "componentName" $componentName) | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "common.fullComponentName" (dict "rootCtx" $rootCtx "componentName" $componentName) }}
  minReplicas: {{ $hpaValues.autoscaling.minReplicas }}
  maxReplicas: {{ $hpaValues.autoscaling.maxReplicas }}
  metrics:
    {{- if $hpaValues.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ $hpaValues.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if $hpaValues.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ $hpaValues.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
{{- end }}

{{/*
`common.hpa` merges the hpa definition in `common.hpa.tpl` with overrides defined the helm values.
This takes a dict with the following keys:
- .rootCtx: the root context
- (optional) .hpaValues: the portion of the Helm values map for the hpa. Defaults to the root values (`.Values`)
- (optional) .hpaOverrides: the template name of the hpa overrides defined by the application chart
*/}}
{{- define "common.hpa" -}}
{{- $rootCtx := .rootCtx -}}
{{- $hpaValues := .hpaValues | default $rootCtx.Values -}}
{{- $hpaOverrides := .hpaOverrides | default "common.defaultEmptyOverrides" -}}
{{- $componentName := .componentName | default "" -}}
{{- include "common.util.merge" (dict "rootCtx" $rootCtx "templateValues" $hpaValues "sourceTemplate" "common.hpa.tpl" "overridesTemplate" $hpaOverrides "componentName" $componentName) -}}
{{- end -}}
