{{/*
`common.httpRoute.tpl` defines a hpa definition.
See: https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1.HTTPRoute
This takes a dict with the following keys:
- .rootCtx: the root context
- (optional) .httpRouteValues: the portion of the Helm values map for the httpRoute. Defaults to the root values (`.Values`)
- (optional) .componentName: the component name if this is part of a multi-component app
*/}}
{{- define "common.httpRoute.tpl" -}}
{{- $rootCtx := .rootCtx -}}
{{- $httpRouteValues := .templateValues | default $rootCtx.Values -}}
{{- $componentName := .componentName | default "" -}}
{{- if $httpRouteValues.httpRoute.enabled -}}
{{- $serviceHostname := $httpRouteValues.httpRoute.serviceHostname | default (include "common.fullComponentName" (dict "rootCtx" $rootCtx "componentName" $componentName)) -}}
{{- $gatewayHostname := $httpRouteValues.httpRoute.gatewayHostname | default $rootCtx.Values.global.gateway.hostname -}}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ include "common.fullComponentName" (dict "rootCtx" $rootCtx "componentName" $componentName) }}
  namespace: {{ $rootCtx.Release.Namespace | quote }}
  labels:
    {{- include "common.labels" $rootCtx | nindent 4 }}
    {{- include "common.componentLabels" (dict "rootCtx" $rootCtx "componentName" $componentName) | nindent 4 }}
  annotations:
    link.argocd.argoproj.io/external-link: "https://{{ $serviceHostname }}.{{ $gatewayHostname }}"
spec:
  parentRefs:
    {{- with $httpRouteValues.httpRoute.parentRefs }}
    {{ tpl (toYaml .) $rootCtx | nindent 4 }}
    {{- end }}
  hostnames:
    - "{{ $serviceHostname }}.{{ $gatewayHostname }}"
  rules:
    {{- range $httpRouteValues.httpRoute.rules }}
    - {{ include "common.tpl" (dict "rootCtx" $rootCtx "template" .) | nindent 6 }}
    {{- end }}
{{- end }}
{{- end }}

{{/*
`common.httpRoute` merges the httpRoute definition in `common.httpRoute.tpl` with overrides defined the helm values.
This takes a dict with the following keys:
- .rootCtx: the root context
- (optional) .httpRouteValues: the portion of the Helm values map for the httpRoute. Defaults to the root values (`.Values`)
- (optional) .httpRouteOverrides: the template name of the httpRoute overrides defined by the application chart
*/}}
{{- define "common.httpRoute" -}}
{{- $rootCtx := .rootCtx -}}
{{- $httpRouteValues := .httpRouteValues | default $rootCtx.Values -}}
{{- $httpRouteOverrides := .httpRouteOverrides | default "common.defaultEmptyOverrides" -}}
{{- $componentName := .componentName | default "" -}}
{{- include "common.util.merge" (dict "rootCtx" $rootCtx "templateValues" $httpRouteValues "sourceTemplate" "common.httpRoute.tpl" "overridesTemplate" $httpRouteOverrides "componentName" $componentName) -}}
{{- end -}}
