{{/*
`common.pdb.tpl` defines a pdb definition.
See: https://kubernetes.io/docs/reference/kubernetes-api/policy-resources/pod-disruption-budget-v1/#PodDisruptionBudget
This takes a dict with the following keys:
- .rootCtx: the root context
- (optional) .pdbValues: the portion of the Helm values map for the pdb. Defaults to the root values (`.Values`)
- (optional) .componentName: the component name if this is part of a multi-component app
*/}}
{{- define "common.pdb.tpl" -}}
{{- $rootCtx := .rootCtx -}}
{{- $pdbValues := .templateValues | default $rootCtx.Values -}}
{{- $componentName := .componentName | default "" -}}
{{- if $pdbValues.pdb.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "common.fullComponentName" (dict "rootCtx" $rootCtx "componentName" $componentName) }}
  namespace: {{ $rootCtx.Release.Namespace | quote }}
  labels:
    {{- include "common.labels" $rootCtx | nindent 4 }}
    {{- include "common.componentLabels" (dict "rootCtx" $rootCtx "componentName" $componentName) | nindent 4 }}
spec:
  {{- with $pdbValues.pdb.minAvailable }}
  minAvailable: {{ . | int }}
  {{- else }}
  maxUnavailable: {{ $pdbValues.pdb.maxUnavailable | int }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "common.selectorLabels" $rootCtx | nindent 6 }}
      {{- include "common.componentSelectorLabels" (dict "rootCtx" $rootCtx "componentName" $componentName) | nindent 6 }}
{{- end }}
{{- end }}

{{/*
`common.pdb` merges the pdb definition in `common.pdb.tpl` with overrides defined the helm values.
This takes a dict with the following keys:
- .rootCtx: the root context
- (optional) .pdbValues: the portion of the Helm values map for the pdb. Defaults to the root values (`.Values`)
- (optional) .pdbOverrides: the template name of the pdb overrides defined by the application chart
*/}}
{{- define "common.pdb" -}}
{{- $rootCtx := .rootCtx -}}
{{- $pdbValues := .pdbValues | default $rootCtx.Values -}}
{{- $pdbOverrides := .pdbOverrides | default "common.defaultEmptyOverrides" -}}
{{- $componentName := .componentName | default "" -}}
{{- include "common.util.merge" (dict "rootCtx" $rootCtx "templateValues" $pdbValues "sourceTemplate" "common.pdb.tpl" "overridesTemplate" $pdbOverrides "componentName" $componentName) -}}
{{- end -}}
