{{/*
`common.sealedSecret.tpl` defines a secret definition.
See: https://github.com/bitnami-labs/sealed-secrets#readme
This takes a dict with the following keys:
- .rootCtx: the root context
- (optional) .secretValues: the portion of the Helm values map for the sealedSecret. Defaults to the root values (`.Values`)
- (optional) .componentName: the component name if this is part of a multi-component app
*/}}
{{- define "common.sealedSecret.tpl" -}}
{{- $rootCtx := .rootCtx -}}
{{- $secretValues := .templateValues | default $rootCtx.Values -}}
{{- $componentName := .componentName | default "" -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: "{{ include "common.fullComponentName" (dict "rootCtx" $rootCtx "componentName" $componentName) }}-{{ $secretValues.name }}"
  namespace: {{ $rootCtx.Release.Namespace | quote }}
  labels:
    {{- include "common.labels" $rootCtx | nindent 4 }}
    {{- include "common.componentLabels" (dict "rootCtx" $rootCtx "componentName" $componentName) | nindent 4 }}
spec:
  {{- with $secretValues.template }}
  template:
    {{- include "common.tpl" (dict "rootCtx" $rootCtx "template" .) | nindent 4 }}
  {{- end }}
  {{- with $secretValues.encryptedData }}
  encryptedData:
    {{- tpl (toYaml .) $rootCtx | nindent 4 }}
  {{- end }}
{{- end }}

{{/*
`common.sealedSecret` merges the sealedSecret definition in `common.sealedSecret.tpl` with overrides defined the helm values.
This takes a dict with the following keys:
- .rootCtx: the root context
- (optional) .secretValues: the portion of the Helm values map for the sealedSecret. Defaults to the root values (`.Values`)
- (optional) .secretOverrides: the template name of the sealedSecret overrides defined by the application chart
*/}}
{{- define "common.sealedSecret" -}}
{{- $rootCtx := .rootCtx -}}
{{- $secretValues := .secretValues | default $rootCtx.Values -}}
{{- $secretOverrides := .secretOverrides | default "common.defaultEmptyOverrides" -}}
{{- $componentName := .componentName | default "" -}}
{{- include "common.util.merge" (dict "rootCtx" $rootCtx "templateValues" $secretValues "sourceTemplate" "common.sealedSecret.tpl" "overridesTemplate" $secretOverrides "componentName" $componentName) -}}
{{- end -}}
