{{/*
`common.serviceAccount.tpl` defines a service account definition.
See: https://kubernetes.io/docs/reference/kubernetes-api/authentication-resources/service-account-v1/
This takes a dict with the following keys:
- .rootCtx: the root context
- (optional) .serviceAccountValues: the portion of the Helm values map for the service account. Defaults to the root values (`.Values`)
- (optional) .componentName: the component name if this is part of a multi-component app
*/}}
{{- define "common.serviceAccount.tpl" -}}
{{- $rootCtx := .rootCtx -}}
{{- $serviceAccountValues := .templateValues | default $rootCtx.Values -}}
{{- $componentName := .componentName | default "" -}}
{{- if $serviceAccountValues.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "common.serviceAccountName" (dict "rootCtx" $rootCtx "componentName" $componentName "serviceAccountValues" $serviceAccountValues) }}
  namespace: {{ $rootCtx.Release.Namespace | quote }}
  labels:
    {{- include "common.labels" $rootCtx | nindent 4 }}
    {{- include "common.componentLabels" . | nindent 4 }}
  {{- with $serviceAccountValues.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}

{{/*
`common.serviceAccount` merges the service definition in `common.serviceAccount.tpl` with overrides defined the helm values.
This takes a dict with the following keys:
- .rootCtx: the root context
- (optional) .serviceAccountValues: the portion of the Helm values map for the service account. Defaults to the root values (`.Values`)
- (optional) .serviceAccountOverrides: the template name of the service account overrides defined by the application chart
*/}}
{{- define "common.serviceAccount" -}}
{{- $rootCtx := .rootCtx -}}
{{- $serviceAccountValues := .serviceAccountValues | default $rootCtx.Values -}}
{{- $serviceAccountOverrides := .serviceAccountOverrides | default "common.defaultEmptyOverrides" -}}
{{- $componentName := .componentName | default "" -}}
{{- include "common.util.merge" (dict "rootCtx" $rootCtx "templateValues" $serviceAccountValues "sourceTemplate" "common.serviceAccount.tpl" "overridesTemplate" $serviceAccountOverrides "componentName" $componentName) -}}
{{- end -}}
