{{/*
`common.tlsRoute.tpl` defines a hpa definition.
See: https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1.tlsRoute
This takes a dict with the following keys:
- .rootCtx: the root context
- (optional) .tlsRouteValues: the portion of the Helm values map for the tlsRoute. Defaults to the root values (`.Values`)
- (optional) .componentName: the component name if this is part of a multi-component app
*/}}
{{- define "common.tlsRoute.tpl" -}}
{{- $rootCtx := .rootCtx -}}
{{- $tlsRouteValues := .templateValues | default $rootCtx.Values -}}
{{- $componentName := .componentName | default "" -}}
{{- if $tlsRouteValues.tlsRoute.enabled -}}
{{- $serviceHostname := $tlsRouteValues.tlsRoute.serviceHostname | default (include "common.fullComponentName" (dict "rootCtx" $rootCtx "componentName" $componentName)) -}}
{{- $gatewayHostname := $tlsRouteValues.tlsRoute.gatewayHostname | default $rootCtx.Values.global.gateway.hostname -}}
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: {{ include "common.fullComponentName" (dict "rootCtx" $rootCtx "componentName" $componentName) }}
  namespace: {{ $rootCtx.Release.Namespace | quote }}
  labels:
    {{- include "common.labels" $rootCtx | nindent 4 }}
    {{- include "common.componentLabels" (dict "rootCtx" $rootCtx "componentName" $componentName) | nindent 4 }}
  annotations:
    link.argocd.argoproj.io/external-link: "https://{{ $serviceHostname }}.{{ $gatewayHostname }}"
spec:
  parentRefs:
    {{- with $tlsRouteValues.tlsRoute.parentRefs }}
    {{ tpl (toYaml .) $rootCtx | nindent 4 }}
    {{- end }}
  hostnames:
    - "{{ $serviceHostname }}.{{ $gatewayHostname }}"
  rules:
    - backendRefs:
        - name: {{ include "common.fullComponentName" (dict "rootCtx" $rootCtx "componentName" $componentName) }}
          port: {{ $tlsRouteValues.service.port }}
{{- end }}
{{- end }}

{{/*
`common.tlsRoute` merges the tlsRoute definition in `common.tlsRoute.tpl` with overrides defined the helm values.
This takes a dict with the following keys:
- .rootCtx: the root context
- (optional) .tlsRouteValues: the portion of the Helm values map for the tlsRoute. Defaults to the root values (`.Values`)
- (optional) .tlsRouteOverrides: the template name of the tlsRoute overrides defined by the application chart
*/}}
{{- define "common.tlsRoute" -}}
{{- $rootCtx := .rootCtx -}}
{{- $tlsRouteValues := .tlsRouteValues | default $rootCtx.Values -}}
{{- $tlsRouteOverrides := .tlsRouteOverrides | default "common.defaultEmptyOverrides" -}}
{{- $componentName := .componentName | default "" -}}
{{- include "common.util.merge" (dict "rootCtx" $rootCtx "templateValues" $tlsRouteValues "sourceTemplate" "common.tlsRoute.tpl" "overridesTemplate" $tlsRouteOverrides "componentName" $componentName) -}}
{{- end -}}
