apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lldap.fullname" . }}
  labels:
    {{- include "lldap.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "lldap.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "lldap.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "lldap.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: UID
              value: {{ .Values.uid | quote }}
            - name: GID
              value: {{ .Values.gid | quote }}
            - name: TZ
              value: {{ .Values.timezone | quote }}
            - name: LLDAP_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.jwtSecret.secretName | quote }}
                  key: {{ .Values.jwtSecret.key | quote }}
            - name: LLDAP_LDAP_BASE_DN
              value: {{ .Values.baseDn | quote }}
            - name: LLDAP_LDAP_USER_DN
              value: {{ .Values.userDn | quote }}
            - name: LLDAP_LDAP_USER_EMAIL
              value: {{ .Values.userEmail | quote }}
            - name: LLDAP_LDAP_USER_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.userPasswordSecret.secretName | quote }}
                  key: {{ .Values.userPasswordSecret.key | quote }}
            - name: LLDAP_SERVER_KEY_SEED
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.keySeedSecret.secretName | quote }}
                  key: {{ .Values.keySeedSecret.key | quote }}
            {{- if .Values.externalDatabase.enabled }}
            - name: LLDAP_DATABASE_URL
              value: {{ .Values.externalDatabase.url }}
            {{- end }}
            {{- if .Values.ldaps.enabled }}
            - name: LLDAP_LDAPS_OPTIONS__ENABLED
              value: "true"
            - name: LLDAP_LDAPS_OPTIONS__PORT
              value: {{ .Values.service.ldaps.port | quote }}
            - name: LLDAP_LDAPS_OPTIONS__CERT_FILE
              value: /etc/ldaps-certs/cert.pem
            - name: LLDAP_LDAPS_OPTIONS__KEY_FILE
              value: /etc/ldaps-certs/key.pem
            {{- end }}
            {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: ldap
              containerPort: {{ .Values.service.ldap.port }}
              protocol: TCP
            {{- if .Values.ldaps.enabled }}
            - name: ldaps
              containerPort: {{ .Values.service.ldaps.port }}
              protocol: TCP
            {{- end }}
            - name: http
              containerPort: {{ .Values.service.web.port }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /data
            {{- if .Values.ldaps.enabled }}
            - name: ldaps-certs
              mountPath: /etc/ldaps-certs
              readOnly: true
            {{- end }}
            {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        - name: data
          persistentVolumeClaim:
            {{- if .Values.persistence.existingClaimName }}
            claimName: {{ .Values.persistence.existingClaimName | quote }}
            {{- else }}
             claimName: {{ include "lldap.fullname" . }}-data
            {{- end }}
        {{- if .Values.ldaps.enabled }}
        - name: ldaps-certs
          secret:
            secretName: {{ .Values.ldaps.secretName | quote }}
            items:
              - key: {{ .Values.ldaps.cert | quote }}
                path: cert.pem
              - key: {{ .Values.ldaps.key | quote }}
                path: key.pem
              - key: {{ .Values.ldaps.ca | quote }}
                path: ca.pem
            defaultMode: 0400
        {{- end }}
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
