kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "lldap.fullname" . }}-data
spec:
  storageClassName: {{ .Values.persistence.storageClassName | quote }}
  accessModes:
    {{ toYaml .Values.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
