apiVersion: v1
kind: Service
metadata:
  name: {{ include "lldap.fullname" . }}
  labels:
    {{- include "lldap.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ldap.port }}
      targetPort: ldap
      protocol: TCP
      appProtocol: tcp
      name: ldap
    {{- if .Values.ldaps.enabled -}}
    - port: {{ .Values.service.ldaps.port }}
      targetPort: ldaps
      protocol: TCP
      appProtocol: tcp
      name: ldaps
    {{- end }}
    - port: {{ .Values.service.web.port }}
      targetPort: http
      protocol: TCP
      appProtocol: tcp
      name: http
  selector:
    {{- include "lldap.selectorLabels" . | nindent 4 }}
