apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "siridb.fullname" . }}
  labels:
    {{- include "siridb.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "siridb.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "siridb.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "siridb.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Values.global.unms.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: tcp-siridb
              containerPort: 9000
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: tcp-siridb
          readinessProbe:
            tcpSocket:
              port: tcp-siridb
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: siridb-data
              mountPath: /var/lib/siridb
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      enableServiceLinks: no
      volumes:
        - name: siridb-data
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
          {{- if .Values.persistence.existingClaim }}
            claimName: {{ .Values.persistence.existingClaim }}
          {{- else }}
            claimName: {{ include "siridb.fullname" . }}
          {{- end }}
        {{- else }}
          emptyDir: {}
        {{- end }}
