{{- if .Values.httpRoute.enabled -}}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ include "kasmweb-chrome.fullname" . }}
spec:
  host: {{ include "kasmweb-chrome.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
  # trafficPolicy:
  #   tls:
  #     mode: SIMPLE
{{- end }}
