{{- if .Values.httpRoute.enabled -}}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ include "kasmweb-chrome.fullname" . }}
  {{- with .Values.httpRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "kasmweb-chrome.labels" . | nindent 4 }}
    {{- with .Values.httpRoute.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  parentRefs:
    {{- toYaml .Values.httpRoute.parentRefs | nindent 4 }}
  hostnames:
    - {{ .Values.httpRoute.hostname | quote }}
  rules:
    - filters:
        - type: RequestHeaderModifier
          requestHeaderModifier:
            set:
              - name: Authorization
                value: Basic a2FzbV91c2VyOnBhc3N3b3Jk
        - type: ResponseHeaderModifier
          responseHeaderModifier:
            set:
              - name: Authorization
                value: Basic a2FzbV91c2VyOnBhc3N3b3Jk
      backendRefs:
        - name: {{ include "kasmweb-chrome.fullname" . }}
          port: {{ .Values.service.web.port }}
{{- end }}
