{{- define "codecov.api.deployment.overrides" -}}
{{- $rootCtx := first . -}}
{{- $componentName := index . 1 -}}
{{- $componentCtx := index . 2 -}}
spec:
  template:
    {{- include "codecov.pod" (list $rootCtx $componentName $componentCtx "codecov.api.pod.overrides") | nindent 4 }}
{{- end -}}

{{- define "codecov.api.pod.overrides" -}}
{{- $rootCtx := first . -}}
{{- $componentName := index . 1 -}}
{{- $componentCtx := index . 2 -}}
spec:
  initContainers:
    - {{- include "codecov.container" (list $rootCtx $componentName $componentCtx "codecov.api.initContainer.overrides") | nindent 6 }}
  containers:
    - {{- include "codecov.container" (list $rootCtx $componentName $componentCtx "codecov.api.container.overrides") | nindent 6 }}
{{- end -}}

{{- define "codecov.api.initContainer.overrides" -}}
{{- $rootCtx := first . -}}
{{- $componentName := index . 1 -}}
{{- $componentCtx := index . 2 -}}
name: codecov-timescale-migration
command:
  - python
args:
  - manage.py
  - migrate
  - --database
  - timeseries
livenessProbe: null
readinessProbe: null
{{- end -}}

{{- define "codecov.api.container.overrides" -}}
{{- $rootCtx := first . -}}
{{- $componentName := index . 1 -}}
{{- $componentCtx := index . 2 -}}

{{- end -}}

{{- $rootCtx := . -}}
{{- $componentName := "api" -}}
{{- $componentCtx := get .Values $componentName -}}
{{- include "codecov.deployment" (list $rootCtx $componentName $componentCtx "codecov.api.deployment.overrides")}}
