{{- define "codecov.api.hpa.overrides" -}}
{{- $rootCtx := first . -}}
{{- $componentName := index . 1 -}}
{{- $componentCtx := index . 2 -}}

{{- end -}}

{{- $rootCtx := . -}}
{{- $componentName := "api" -}}
{{- $componentCtx := get .Values $componentName -}}
{{- include "codecov.hpa" (list $rootCtx $componentName $componentCtx "codecov.api.hpa.overrides")}}
