{{- define "codecov.api.serviceAccount.overrides" -}}
{{- $rootCtx := first . -}}
{{- $componentName := index . 1 -}}
{{- $componentCtx := index . 2 -}}

{{- end -}}

{{- $rootCtx := . -}}
{{- $componentName := "api" -}}
{{- $componentCtx := get .Values $componentName -}}
{{- include "codecov.service" (list $rootCtx $componentName $componentCtx "codecov.api.serviceAccount.overrides")}}
