apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: {{ include "dragonflydb.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "dragonflydb.labels" . | nindent 4 }}
  annotations:
    {{- include "dragonflydb.annotations" . | nindent 4 }}
spec:
  labels:
    {{- include "dragonflydb.selectorLabels" . | nindent 4 }}

  replicas: {{ .Values.replicaCount }}
  image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
  serviceAccountName: {{ include "dragonflydb.serviceAccountName" . }}

  {{- with .Values.args }}
  args:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- with .Values.env }}
  env:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- if .Values.tls.enabled }}
  tlsSecretRef:
    name: "{{ include "dragonflydb.fullname" . }}-server-tls"
  {{- end }}
  
  {{- if .Values.auth.enabled }}
  authentication:
    {{- if eq .Values.auth.mode "password" }}
    passwordFromSecret:
      {{- with .Values.auth.password.existingSecret }}
      name: {{ .name | quote }}
      key: {{ .key | quote }}
      {{- else }}
      name: "{{ include "dragonflydb.fullname" . }}-password"
      key: {{ .Values.auth.password.secretKey | quote }}
      {{- end }}

    {{- else if eq .Values.auth.mode "tls" }}
    {{- if and .Values.tls.enabled .Values.auth.clientCaCertSecret }}
    clientCaCertSecret:
      name: {{ .Values.auth.clientCaCertSecret.name }}
    {{- else }}
    {{- fail ".Values.tls.enabled and .Values.auth.clientCaCertSecret must both be set when .Values.auth.mode is 'password'" }}
    {{- end }}

    {{- else }}
    {{- fail printf "Invalid value for .Values.auth.mode: '%s'. Must be one of 'password', 'tls'" .Values.auth.mode }}

    {{- end }}
  {{- end }}

  {{- with .Values.snapshot }}
  snapshot:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- with .Values.podAnnotations }}
  podAnnotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  resources:
    {{- toYaml .Values.resources | nindent 4 }}
  
  {{- with .Values.affinity }}
  affinity:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- with .Values.tolerations }}
  tolerations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- if gt (.Values.replicaCount | int) 1 }}
  {{- with .Values.topologySpreadConstraints }}
  topologySpreadConstraints:
    {{- range . }}
    - {{- toYaml . | nindent 6 }}
      {{- if not .labelSelector }}
      labelSelector:
        matchLabels:
          {{ include "dragonflydb.selectorLabels" $ | nindent 10 }}
      {{- end }}
    {{- end }}
  {{- end }}
  {{- end }}
