uid: 1000
gid: 1000
timezone: UTC

jwtSecret:
  # Name of existing secret
  secretName: ""
  # Key inside secret
  key: jwt

baseDn: dc=example,dc=com
userDn: admin
userEmail: admin@example.com

userPasswordSecret:
  # Name of existing secret
  secretName: ""
  # Key inside secret
  key: password

keySeedSecret:
  # Name of existing secret
  secretName: ""
  # Key inside secret
  key: password

ldaps:
  enabled: false
  secretName: ""
  cert: tls.crt
  key: tls.key
  ca: ca.crt

# Use external database rather than built-in sqlite
externalDatabase:
  enabled: false
  # Fully qualified connection string
  # url: mysql://mysql-user:password@mysql-server/my-database
  # url: postgres://postgres-user:password@postgres-server/my-database
  url: ""

replicaCount: 1

image:
  repository: nitnelave/lldap
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  ldap:
    port: 3890
  ldaps:
    port: 6360
  web:
    port: 17170

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

httpRoute:
  enabled: false
  hostname: ""
  annotations: {}
  labels: {}
  parentRefs: []
    # - name: my-gateway
    #   namespace: gateway-namespace
    #   sectionName: https

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

persistence:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  size: 1Gi
  # Use an existing claim rather than creating one
  existingClaimName: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

extraEnv: []
  # - name: PGPASSFILE
  #   value: /etc/pgpass/.pgpass

extraVolumes: []
  # - name: db-tls
  #   secret:
  #     secretName: postgres-tls
  #     defaultMode: 0400

extraVolumeMounts: []
  # - name: db-tls
  #   mountPath: /etc/postgres-tls
  #   readOnly: true
