apiVersion: v1
kind: Service
metadata:
  name: {{ include "netflow.fullname" . }}
  labels:
    {{- include "netflow.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: udp
      protocol: {{ .Values.service.protocol }}
      name: udp
  selector:
    {{- include "netflow.selectorLabels" . | nindent 4 }}
