{{- if (eq .Values.tls.mode "certManager") }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "{{ include "postgresql.fullname" . }}-server-tls"
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    {{- mustMergeOverwrite (dict "argocd.argoproj.io/sync-wave" "0") (include "postgresql.annotations" . | fromYaml) | toYaml | nindent 4 }}
spec:
  secretName: "{{ include "postgresql.fullname" . }}-server-tls"
  secretTemplate:
    labels:
      cnpg.io/reload: ""
  duration: 2160h0m0s # 90d
  renewBefore: 360h0m0s # 15d
  revisionHistoryLimit: 10
  subject:
    organizations:
      - benfu-me
  privateKey:
    algorithm: Ed25519
    encoding: PKCS8
    rotationPolicy: Always
  usages:
    - digital signature
    - key encipherment
    - server auth
    - client auth
  dnsNames:
    - "{{ include "postgresql.fullname" . }}-rw"
    - "{{ include "postgresql.fullname" . }}-rw.{{ .Release.Namespace }}"
    - "{{ include "postgresql.fullname" . }}-rw.{{ .Release.Namespace }}.svc"
    - "{{ include "postgresql.fullname" . }}-r"
    - "{{ include "postgresql.fullname" . }}-r.{{ .Release.Namespace }}"
    - "{{ include "postgresql.fullname" . }}-r.{{ .Release.Namespace }}.svc"
    - "{{ include "postgresql.fullname" . }}-ro"
    - "{{ include "postgresql.fullname" . }}-ro.{{ .Release.Namespace }}"
    - "{{ include "postgresql.fullname" . }}-ro.{{ .Release.Namespace }}.svc"
    {{- if eq .Values.tls.profile "cnpg" }}
    - "{{ include "postgresql.fullname" . }}-rw.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}"
    - "{{ include "postgresql.fullname" . }}-r.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}"
    - "{{ include "postgresql.fullname" . }}-ro.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}"
    {{- end }}
    {{- range concat (include "postgresql.poolerDNSNames" . | fromJsonArray) .Values.tls.serverAltDNSNames }}
    - {{ . | quote }}
    {{- end }}
  issuerRef:
    {{- include "postgresql.issuerRef" . | nindent 4 }}
{{- end }}
