{{- if and (eq .Values.tls.mode "certManager") .Values.tls.superuserCertificate }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "{{ include "postgresql.fullname" . }}-client-superuser-tls"
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    {{- mustMergeOverwrite (dict "argocd.argoproj.io/sync-wave" "0") (include "postgresql.annotations" . | fromYaml) | toYaml | nindent 4 }}
spec:
  secretName: "{{ include "postgresql.fullname" . }}-client-superuser-tls"
  duration: 2160h0m0s # 90d
  renewBefore: 360h0m0s # 15d
  revisionHistoryLimit: 10
  subject:
    organizations:
      - benfu-me
  privateKey:
    algorithm: Ed25519
    encoding: PKCS8
    rotationPolicy: Always
  usages:
    - digital signature
    - key encipherment
    - client auth
  commonName: postgres
  dnsNames:
    - postgres
  issuerRef:
    {{- include "postgresql.issuerRef" . | nindent 4 }}
{{- end }}
