{{- if .Values.backup.objectBucket.enabled }}
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: "{{ include "postgresql.fullname" . }}-backup-bucket"
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    {{- include "postgresql.annotations" . | nindent 4 }}
spec:
  bucketName: "{{ include "postgresql.fullname" . }}-backup"
  storageClassName: {{ include "postgresql.bucketStorageClassName" . | quote }}
{{- end }}
