{{- if .Values.httpRoute.enabled -}}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ include "unifi-network-application.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "unifi-network-application.labels" . | nindent 4 }}
spec:
  host: "{{ include "unifi-network-application.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local"
  trafficPolicy:
    portLevelSettings:
      - port:
          number: 8443
        tls:
          mode: SIMPLE
          insecureSkipVerify: true
{{- end }}
