{{- if .Values.httpRoute.enabled -}}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ include "unifi-network-application.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  {{- with .Values.httpRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "unifi-network-application.labels" . | nindent 4 }}
    {{- with .Values.httpRoute.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  parentRefs:
    {{- toYaml .Values.httpRoute.parentRefs | nindent 4 }}
  hostnames:
    - {{ .Values.httpRoute.hostname | quote }}
  rules:
    - backendRefs:
        - name: {{ include "unifi-network-application.fullname" . }}
          port: 8443
{{- end }}
