apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "unifi-network-application.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "unifi-network-application.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "unifi-network-application.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "unifi-network-application.fullname" . }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "unifi-network-application.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "unifi-network-application.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: Etc/UTC
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mongodb.existingSecretName | quote }}
                  key: username
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mongodb.existingSecretName | quote }}
                  key: password
            - name: MONGO_HOST
              value: {{ .Values.mongodb.host | quote }}
            - name: MONGO_PORT
              value: {{ .Values.mongodb.port | quote }}
            - name: MONGO_DBNAME
              value: {{ .Values.mongodb.dbName | quote }}
            {{- with .Values.memoryLimit }}
            - name: MEM_LIMIT
              value: "{{ . | quote }}"
            - name: MEM_STARTUP
              value: "{{ . | quote }}"
            {{- end }}
          ports:
            - name: stun
              protocol: UDP
              containerPort: 3478
            - name: discovery
              protocol: UDP
              containerPort: 10001
            - name: controller
              protocol: TCP
              containerPort: 8080
            - name: gui
              protocol: TCP
              containerPort: 8443
            - name: l2
              protocol: UDP
              containerPort: 1900
            - name: guest-http
              protocol: TCP
              containerPort: 8880
            - name: guest-https
              protocol: TCP
              containerPort: 8843
            - name: speedtest
              protocol: TCP
              containerPort: 6789
            - name: syslog
              protocol: TCP
              containerPort: 5514
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: "{{ include "unifi-network-application.fullname" . }}-data"
              mountPath: /config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

  volumeClaimTemplates:
    - metadata:
        name: "{{ include "unifi-network-application.fullname" . }}-data"
      spec:
        accessModes:
          {{ toYaml .Values.persistence.accessModes | nindent 10 }}
        storageClassName: {{ .Values.persistence.storageClassName | quote }}
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}
