image:
  tag: "18.6-system-trixie"
clientUsername: app
databaseName: app
userCredsSecretName: example-app
backup:
  volumeSnapshot:
    className: database-snapshots
    snapshotOwnerReference: backup
  scheduled:
    enabled: true
    method: volumeSnapshot
