apiVersion: v1
kind: Service
metadata:
  name: {{ include "fluentd.fullname" . }}
  labels:
    {{- include "fluentd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: tcp-forward
      port: 24224
      protocol: TCP
  selector:
    {{- include "fluentd.selectorLabels" . | nindent 4 }}
