{{- define "codecov.common.env" -}}
{{- $rootCtx := first . -}}
{{- $componentName := index . 1 -}}
{{- $componentCtx := index . 2 -}}
# Common environment variables for all components
- name: SETUP__HTTP__COOKIE_SECRET
  valueFrom:
    secretKeyRef:
      {{- if $rootCtx.Values.cookieSecretSecretName }}
      name: {{ $rootCtx.Values.cookieSecretSecretName | quote }}
      {{- else }}
      name: "{{ include "codecov.fullname" $rootCtx }}-cookie-secret"
      {{- end }}
      key: {{ $rootCtx.Values.cookieSecretSecretKey }}
- name: SERVICES__DATABASE_URL
  valueFrom:
    secretKeyRef:
      {{- if $rootCtx.Values.databaseUrlSecretName }}
      name: {{ $rootCtx.Values.databaseUrlSecretName | quote }}
      {{- else }}
      name: "{{ include "codecov.fullname" $rootCtx }}-database-url"
      {{- end }}
      key: {{ $rootCtx.Values.databaseUrlSecretKey }}
- name: SERVICES__TIMESERIES_DATABASE_URL
  valueFrom:
    secretKeyRef:
      {{- if $rootCtx.Values.timescaledbUrlSecretName }}
      name: {{ $rootCtx.Values.timescaledbUrlSecretName | quote }}
      {{- else }}
      name: "{{ include "codecov.fullname" $rootCtx }}-timescaledb-url"
      {{- end }}
      key: {{ $rootCtx.Values.timescaledbUrlSecretKey }}
- name: SERVICES__REDIS_URL
  valueFrom:
    secretKeyRef:
      {{- if $rootCtx.Values.redisUrlSecretName }}
      name: {{ $rootCtx.Values.redisUrlSecretName | quote }}
      {{- else }}
      name: "{{ include "codecov.fullname" $rootCtx }}-redis-url"
      {{- end }}
      key: {{ $rootCtx.Values.redisUrlSecretKey }}
{{- if $rootCtx.Values.oauth.enabled }}
- name: "{{ $rootCtx.Values.oauth.provider | upper }}__CLIENT_ID"
  valueFrom:
    secretKeyRef:
      {{- if $rootCtx.Values.oauth.clientCredentialsSecretName }}
      name: {{ $rootCtx.Values.oauth.clientCredentialsSecretName | quote }}
      {{- else }}
      name: "{{ include "codecov.fullname" $rootCtx }}-oauth-client-credentials"
      {{- end }}
      key: {{ $rootCtx.Values.oauth.clientCredentialsClientIdSecretKey }}
- name: "{{ $rootCtx.Values.oauth.provider | upper }}__CLIENT_SECRET"
  valueFrom:
    secretKeyRef:
      {{- if $rootCtx.Values.oauth.clientCredentialsSecretName }}
      name: {{ $rootCtx.Values.oauth.clientCredentialsSecretName | quote }}
      {{- else }}
      name: "{{ include "codecov.fullname" $rootCtx }}-oauth-client-credentials"
      {{- end }}
      key: {{ $rootCtx.Values.oauth.clientCredentialsClientSecretSecretKey }}
{{- end }}
{{- if and $rootCtx.Values.minio.enabled $rootCtx.Values.minio.accessKeyAuth.enabled }}
- name: SERVICES__MINIO__ACCESS_KEY_ID
  valueFrom:
    secretKeyRef:
      {{- if $rootCtx.Values.minio.accessKeyAuth.accessCredentialsSecretName }}
      name: {{ $rootCtx.Values.minio.accessKeyAuth.accessCredentialsSecretName | quote }}
      {{- else }}
      name: "{{ include "codecov.fullname" $rootCtx }}-minio-credentials"
      {{- end }}
      key: {{ $rootCtx.Values.minio.accessKeyAuth.accessCredentialsAccessKeyIdSecretKey }}
- name: SERVICES__MINIO__SECRET_ACCESS_KEY
  valueFrom:
    secretKeyRef:
      {{- if $rootCtx.Values.minio.accessKeyAuth.accessCredentialsSecretName }}
      name: {{ $rootCtx.Values.minio.accessKeyAuth.accessCredentialsSecretName | quote }}
      {{- else }}
      name: "{{ include "codecov.fullname" $rootCtx }}-minio-credentials"
      {{- end }}
      key: {{ $rootCtx.Values.minio.accessKeyAuth.accessCredentialsSecretAccessKeySecretKey }}
{{- end }}
{{- end }}

{{- define "codecov.container.tpl" -}}
{{- $rootCtx := first . -}}
{{- $componentName := index . 1 -}}
{{- $componentCtx := index . 2 -}}
name: {{ $rootCtx.Chart.Name }}
securityContext:
  {{- toYaml $componentCtx.securityContext | nindent 2 }}
image: "{{ $componentCtx.image.repository }}:{{ $componentCtx.image.tag | default $rootCtx.Chart.AppVersion }}"
imagePullPolicy: {{ $componentCtx.image.pullPolicy }}
env:
  {{- include "codecov.common.env" . | nindent 2 }}
  {{- with $componentCtx.extraEnv }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- with $componentCtx.extraEnvFrom }}
envFrom:
  {{- toYaml . | nindent 2 }}
{{- end }}
ports:
  - name: http
    containerPort: {{ $componentCtx.service.port }}
    protocol: TCP
livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http
resources:
  {{- toYaml $componentCtx.resources | nindent 2 }}
volumeMounts:
  - name: config
    mountPath: /config/codecov.yml
    subPath: codecov.yml
  {{- with $componentCtx.extraVolumeMounts }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end -}}

{{- define "codecov.container" -}}
{{- $rootCtx := first . -}}
{{- $componentName := index . 1 -}}
{{- $componentCtx := index . 2 -}}
{{- include "codecov.util.merge" (append . "codecov.container.tpl") -}}
{{- end -}}
