{{- define "codecov.pod.tpl" -}}
{{- $rootCtx := first . -}}
{{- $componentName := index . 1 -}}
{{- $componentCtx := index . 2 -}}
metadata:
  annotations:
    checksum/config: {{ tpl (mergeOverwrite (mustDeepCopy ($rootCtx.Files.Get "config/codecov.yml" | fromYaml)) (mustDeepCopy $rootCtx.Values.config) | toYaml) $rootCtx | sha256sum }}
    {{- with $componentCtx.podAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "codecov.componentSelectorLabels" . | nindent 4 }}
spec:
  {{- with $componentCtx.imagePullSecrets }}
  imagePullSecrets:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  enableServiceLinks: false
  serviceAccountName: "{{ include "codecov.serviceAccountName" $rootCtx }}-{{ $componentName }}"
  securityContext:
    {{- toYaml $componentCtx.podSecurityContext | nindent 4 }}
  containers:
    - {{- include "codecov.container.tpl" (list $rootCtx $componentName $componentCtx) | nindent 6 }}
  {{- with $componentCtx.nodeSelector }}
  nodeSelector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $componentCtx.affinity }}
  affinity:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $componentCtx.tolerations }}
  tolerations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $componentCtx.topologySpreadConstraints }}
  topologySpreadConstraints:
    {{- tpl . $rootCtx | nindent 4 }}
  {{- end }}
  volumes:
    - name: config
      configMap:
        name: {{ include "codecov.fullname" $rootCtx }}
        items:
          - key: codecov.yml
            path: codecov.yml
    {{- if and $rootCtx.Values.oauth.enabled $rootCtx.Values.githubIntegration.enabled }}
    - name: github-integration-pem
      secret:
        {{- if $rootCtx.Values.githubIntegration.privateKeySecretName }}
        secretName: {{ $rootCtx.Values.githubIntegration.privateKeySecretName | quote }}
        {{- else }}
        secretName: "{{ include "codecov.fullname" $rootCtx }}-github-private-key"
        {{- end }}
        defaultMode: 0400
    {{- end }}
    {{- with $componentCtx.extraVolumes }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end -}}

{{- define "codecov.pod" -}}
{{- $rootCtx := first . -}}
{{- $componentName := index . 1 -}}
{{- $componentCtx := index . 2 -}}
{{- include "codecov.util.merge" (append . "codecov.pod.tpl") -}}
{{- end -}}
