{{- define "codecov.serviceAccount.tpl" -}}
{{- $rootCtx := first . -}}
{{- $componentName := index . 1 -}}
{{- $componentCtx := index . 2 -}}
{{- if $componentCtx.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ include "codecov.serviceAccountName" $rootCtx }}-{{ $componentName }}"
  namespace: {{ $rootCtx.Release.Namespace | quote }}
  labels:
    {{- include "codecov.componentLabels" . | nindent 4 }}
  {{- with $componentCtx.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}

{{- define "codecov.serviceAccount" -}}
{{- $rootCtx := first . -}}
{{- $componentName := index . 1 -}}
{{- $componentCtx := index . 2 -}}
{{- include "codecov.util.merge" (append . "codecov.serviceAccount.tpl") -}}
{{- end -}}
