{{- if and (.Values.oauth.enabled) (not .Values.oauth.clientCredentialsSecretName) -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "codecov.fullname" . }}-oauth-client-credentials"
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "codecov.labels" . | nindent 4 }}
data:
  clientId: {{ required ".Values.oauth.clientId must be set when oauth is enabled" .Values.oauth.clientId | b64enc }}
  clientSecret: {{ required ".Values.oauth.clientSecret must be set when oauth is enabled" .Values.oauth.clientSecret | b64enc }}
{{- end }}
