{{- if and (.Values.minio.enabled) (.Values.minio.accessKeyAuth.enabled) (not .Values.minio.accessKeyAuth.accessCredentialsSecretName) -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "codecov.fullname" . }}-minio-credentials"
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "codecov.labels" . | nindent 4 }}
data:
  {{ .Values.minio.accessKeyAuth.accessCredentialsAccessKeyIdSecretKey }}: {{ required ".Values.minio.accessKeyAuth.accessKeyId must be set when minio access key auth is enabled" .Values.minio.accessKeyAuth.accessKeyId | b64enc }}
  {{ .Values.minio.accessKeyAuth.accessCredentialsSecretAccessKeySecretKey }}: {{ required ".Values.minio.accessKeyAuth.secretAccessKey must be set when minio access key auth is enabled" .Values.minio.accessKeyAuth.secretAccessKey | b64enc }}
{{- end }}
