{{- if and (.Values.oauth.enabled) (.Values.globalUploadToken.enabled) (not .Values.globalUploadToken.tokenSecretName) -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "codecov.fullname" . }}-global-upload-token"
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "codecov.labels" . | nindent 4 }}
data:
  {{ .Values.globalUploadToken.tokenSecretKey }}: {{ required ".Values.globalUploadToken.token is required when global upload token is enabled" .Values.globalUploadToken.token | b64enc }}
{{- end }}
