{{- if not .Values.databaseUrlSecretName -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "codecov.fullname" . }}-database-url"
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "codecov.labels" . | nindent 4 }}
data:
  url: {{ required "Regex match for database URL failed" (mustRegexFind .Values.databaseUrlRegexMatch .Values.databaseUrl) | b64enc }}
{{- end }}
