{{- if not .Values.timescaledbUrlSecretName -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "codecov.fullname" . }}-timescaledb-url"
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "codecov.labels" . | nindent 4 }}
data:
  {{ .Values.timescaledbUrlSecretKey }}: {{ required "Regex match for timescaledb URL failed" (mustRegexFind .Values.timescaledbUrlRegexMatch .Values.timescaledbUrl) | b64enc }}
{{- end }}
