{{- if not .Values.cookieSecretSecretName -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "codecov.fullname" . }}-cookie-secret"
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "codecov.labels" . | nindent 4 }}
data:
  cookieSecret: {{ .Values.cookieSecret | default (randAlphaNum 32) | b64enc }}
{{- end }}
