apiVersion: v1
kind: Service
metadata:
  name: {{ include "unms.fullname" . }}
  labels:
    {{- include "unms.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: 8081
      protocol: TCP
    - name: http-ws
      port: 8082
      protocol: TCP
    - name: http-shell
      port: 8083
      protocol: TCP
    - name: http-api
      port: 8084
      protocol: TCP
  selector:
    {{- include "unms.selectorLabels" . | nindent 4 }}
