{{- define "codecov.worker.deployment.overrides" -}}
{{- $rootCtx := first . -}}
{{- $componentName := index . 1 -}}
{{- $componentCtx := index . 2 -}}
spec:
  template:
    {{- include "codecov.pod" (list $rootCtx $componentName $componentCtx "codecov.worker.pod.overrides") | nindent 4 }}
{{- end -}}

{{- define "codecov.worker.pod.overrides" -}}
{{- $rootCtx := first . -}}
{{- $componentName := index . 1 -}}
{{- $componentCtx := index . 2 -}}
spec:
  containers:
    - {{- include "codecov.container" (list $rootCtx $componentName $componentCtx "codecov.worker.container.overrides") | nindent 6 }}
{{- end -}}

{{- define "codecov.worker.container.overrides" -}}
{{- $rootCtx := first . -}}
{{- $componentName := index . 1 -}}
{{- $componentCtx := index . 2 -}}
env:
  - name: RUN_ENV
    value: enterprise
  {{- include "codecov.common.env" . | nindent 2 }}
  {{- with $componentCtx.extraEnv }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end -}}

{{- $rootCtx := . -}}
{{- $componentName := "worker" -}}
{{- $componentCtx := get .Values $componentName -}}
{{- include "codecov.deployment" (list $rootCtx $componentName $componentCtx "codecov.worker.deployment.overrides")}}
