{{- define "codecov.gateway.deployment.overrides" -}}
{{- $rootCtx := first . -}}
{{- $componentName := index . 1 -}}
{{- $componentCtx := index . 2 -}}

{{- end -}}

{{- $rootCtx := . -}}
{{- $componentName := "gateway" -}}
{{- $componentCtx := get .Values $componentName -}}
{{- include "codecov.deployment" (list $rootCtx $componentName $componentCtx "codecov.gateway.deployment.overrides")}}
