name: Build and Push Charts

on:
  push:
    branches:
      - main

env:
  # https://github.com/kubernetes-sigs/kubectl-validate/releases
  KUBECTL_VALIDATE_VERSION: v0.0.4

jobs:
  build-push:
    name: Build and push charts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chart:
          - chart: common
            version: 0.1.0
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      
      - name: Lint
        run: helm lint charts/${{ matrix.chart.chart }} --strict --debug

      - name: Build chart
        run: |-
          mkdir -p dist/
          helm package charts/${{ matrix.chart.chart }} --destination dist/
      
      - name: Login to the internal helm registry
        run: |-
          echo "${HELM_INTERNAL_REGISTRY_PASSWORD}" | helm registry login registry.benfu.me/helm-internal --username "${HELM_INTERNAL_REGISTRY_USERNAME}" --password-stdin
        env:
          HELM_INTERNAL_REGISTRY_USERNAME: ${{ secrets.HELM_INTERNAL_REGISTRY_USERNAME }}
          HELM_INTERNAL_REGISTRY_PASSWORD: ${{ secrets.HELM_INTERNAL_REGISTRY_PASSWORD }}

      - name: Push chart
        run: |-
          helm push dist/${{ matrix.chart.chart }}-${{ matrix.chart.version }}.tgz oci://registry.benfu.me/helm-internal
